# Generated by Django 3.2.16 on 2024-08-20 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20240819_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='autor',
            new_name='author',
        ),
    ]
